# version: "3.9" # Do not specify, you will get all the benifits of v2,v3 & new version (both for Python & Golang)

services:
  app:
    build:
      context: .
    profiles: ["app"]
    restart: unless-stopped
    deploy:
      replicas: 3

    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine

  nginx:
      build:
        context: .
        dockerfile: DockerfileNginx
      restart: unless-stopped
      ports:
      - "80:80"
      depends_on:
        - db


volumes:
  pgdata:
